# -*- coding: utf-8 -*-
"""export —把模型写成一个 bundle。

产物:
    scene.json / albedo.png / shading.png / roughness.png / metalness.png
    depth16.png / masks/*.png / sky.hdr / blender_preview.py / report.txt
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List

import numpy as np

from . import core
from .light import Lighting, equirect_from_lighting

__all__ = ["write_hdr", "export_bundle", "build_blender_preview"]


# ═══════════════════════════════════════════════════════════════════
# Radiance .hdr（RGBE + RLE）
# ═══════════════════════════════════════════════════════════════════
def _pack_scanline(chan: np.ndarray) -> bytes:
    """Radiance RLE 约定：code>128 → 重复(code-128)次；否则 → 字面量 code 个字节。"""
    out = bytearray()
    n = len(chan)
    i = 0
    while i < n:
        j = i
        while j + 1 < n and chan[j + 1] == chan[i]:
            j += 1
        run = j - i + 1
        if run >= 4:
            while run > 0:
                r = min(run, 127)
                out.append(128 + r)
                out.append(int(chan[i]))
                run -= r
            i = j + 1
            continue
        k = i
        while k < n and (k - i) < 128:
            if k + 3 < n and chan[k] == chan[k + 1] == chan[k + 2] == chan[k + 3]:
                break
            k += 1
        out.append(k - i)
        out.extend(int(v) for v in chan[i:k])
        i = k
    return bytes(out)


def write_hdr(path: str | Path, rgb: np.ndarray) -> str:
    """线性 RGB float → Radiance .hdr（RGBE + 扫描线 RLE）。"""
    rgb = np.clip(np.asarray(rgb, dtype=np.float64), 0.0, None)
    h, w, _ = rgb.shape
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "wb") as f:
        f.write(b"#?RADIANCE\nFORMAT=32-bit_rle_rgbe\n\n")
        f.write(("-Y %d +X %d\n" % (h, w)).encode("ascii"))
        for row in rgb.reshape(-1, w, 3) if rgb.ndim == 3 else rgb:
            mx = row.max(axis=1)
            nz = mx > 1e-32
            rgbe = np.zeros((w, 4), np.uint8)
            if nz.any():
                m, e = np.frexp(mx[nz])
                scale = m * 256.0 / mx[nz]
                for c in range(3):
                    rgbe[nz, c] = np.clip(row[nz, c] * scale, 0, 255).astype(np.uint8)
                rgbe[nz, 3] = np.clip(e + 128, 0, 255).astype(np.uint8)
            f.write(bytes([2, 2, (w >> 8) & 0xFF, w & 0xFF]))
            for c in range(4):
                f.write(_pack_scanline(rgbe[:, c]))
    return str(path)


# ═══════════════════════════════════════════════════════════════════
# Blender 预览脚本
# ═══════════════════════════════════════════════════════════════════
def build_blender_preview(scene: dict) -> str:
    """生成可在 Blender 里复现该环境的脚本（语法必须合法，CI 会编译检查）。"""
    dims = scene["room"]["dims"]
    cam = scene["camera"]["position_in_room"]
    sun = scene["lighting"]
    L = ["# -*- coding: utf-8 -*-",
         '"""Auto-generated by photo2pbr — 一键复现估计出的反射环境。',
         '用法:  blender -b --factory-startup -P blender_preview.py',
         '"""',
         "import json",
         "import math",
         "import os",
         "import bpy",
         "",
         'HERE = os.path.dirname(os.path.abspath(__file__))',
         'SCENE = json.load(open(os.path.join(HERE, "scene.json"), encoding="utf-8"))',
         "",
         "def build():",
         "    D = SCENE['room']['dims']",
         "    C = SCENE['camera']['position_in_room']",
         "    bpy.ops.object.select_all(action='SELECT')",
         "    bpy.ops.object.delete(use_global=False)",
         "    # 房间（内向盒体）",
         "    bpy.ops.mesh.primitive_cube_add(size=1.0, location=(0.0, 0.0, 0.0))",
         "    room = bpy.context.object",
         "    room.name = 'room'",
         "    room.scale = (D[0] / 2.0, D[2] / 2.0, D[1] / 2.0)  # y 上",
         "    # 相机",
         "    cam_data = bpy.data.cameras.new('cam')",
         "    cam_data.lens_unit = 'FOV'",
         "    cam_data.angle = math.radians(SCENE['camera']['fov_deg'])",
         "    cam_obj = bpy.data.objects.new('cam', cam_data)",
         "    bpy.context.collection.objects.link(cam_obj)",
         "    cam_obj.location = (C[0], C[2], -C[1])",
         "    bpy.context.scene.camera = cam_obj",
         "    # 太阳（角径 → 软硬）",
         "    l = bpy.data.lights.new('sun', type='SUN')",
         "    l.energy = 4.0",
         "    if SCENE['lighting'].get('sun_confidence') == 'detected':",
         "        l.angle = math.radians(max(SCENE['lighting']['sun_angular_deg'], 0.1))",
         "    sun_obj = bpy.data.objects.new('sun', l)",
         "    bpy.context.collection.objects.link(sun_obj)",
         "    # 环境（sky.hdr → 真实反射）",
         "    world = bpy.context.scene.world or bpy.data.worlds.new('World')",
         "    bpy.context.scene.world = world",
         "    world.use_nodes = True",
         "    nt = world.node_tree",
         "    for n in list(nt.nodes):",
         "        nt.nodes.remove(n)",
         "    bg = nt.nodes.new('ShaderNodeBackground')",
         "    env = nt.nodes.new('ShaderNodeTexEnvironment')",
         "    out = nt.nodes.new('ShaderNodeOutputWorld')",
         "    hdr = os.path.join(HERE, 'sky.hdr')",
         "    if os.path.exists(hdr):",
         "        env.image = bpy.data.images.load(hdr)",
         "        nt.links.new(env.outputs['Color'], bg.inputs['Color'])",
         "    nt.links.new(bg.outputs['Background'], out.inputs['Surface'])",
         "    # 输出",
         "    sc = bpy.context.scene",
         "    sc.render.engine = 'CYCLES'",
         "    sc.render.resolution_x = 960",
         "    sc.render.resolution_y = 720",
         "    sc.render.filepath = os.path.join(HERE, 'preview.png')",
         "    bpy.ops.render.render(write_still=True)",
         "",
         "",
         "if __name__ == '__main__':",
         "    build()",
         ""]
    return "\n".join(L)


# ═══════════════════════════════════════════════════════════════════
# bundle
# ═══════════════════════════════════════════════════════════════════
def export_bundle(out_dir: str | Path, model: dict, src_path: str, key: str) -> List[str]:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    (out / "masks").mkdir(exist_ok=True)
    files: List[str] = []

    alb = np.asarray(model["albedo"], dtype=np.float64)
    shading = np.asarray(model["shading"], dtype=np.float64)
    rough = np.asarray(model["roughness"], dtype=np.float64)
    metal = np.asarray(model["metalness"], dtype=np.float64)
    geo = model["geometry"]
    light = Lighting(**{k: (tuple(v) if isinstance(v, list) else v)
                        for k, v in model["lighting"].items()})

    files.append(core.save_png(core.linear_to_srgb(alb), out / "albedo.png"))
    # shading 是"相对照度（均值=1）"：显示时按 99 分位归一，避免整片过曝
    sh_disp = np.clip(np.asarray(shading, float)
                      / max(float(np.percentile(shading, 99)), 1e-6), 0.0, 1.0)
    files.append(core.save_png(sh_disp, out / "shading.png"))
    files.append(core.save_png(np.clip(rough, 0, 1), out / "roughness.png"))
    files.append(core.save_png(np.clip(metal, 0, 1), out / "metalness.png"))
    spec = model.get("specular")
    if spec is None:
        spec = np.zeros_like(rough)
    files.append(core.save_png(np.clip(np.asarray(spec, float), 0, 1), out / "specular.png"))

    depth = model.get("depth")
    if depth is not None and np.asarray(depth).size:
        d = np.asarray(depth, dtype=np.float64)
        v = d[d > 0]
        if v.size:
            dn = np.clip(d / max(float(v.max()), 1e-9), 0, 1)
            files.append(core.save_png16(dn, out / "depth16.png"))

    masks = model.get("face_masks") or {}
    for name, m in masks.items():
        files.append(core.save_png(np.asarray(m, np.float32), out / "masks" / f"{name}.png"))

    env = equirect_from_lighting(light)
    files.append(write_hdr(out / "sky.hdr", env))

    # ── 居中化：房间中心为原点，相机位置随之平移
    bmin = np.asarray(geo["bounds_min"], np.float64)
    bmax = np.asarray(geo["bounds_max"], np.float64)
    center = 0.5 * (bmin + bmax)
    cam_pos = (-center).tolist()

    src = Path(src_path)
    scene = {
        "schema": "photo2pbr/scene/1",
        "generator": {"name": "photo2pbr", "version": core.VERSION, "key": key},
        "source": {"path": src.name, "md5": core.md5_file(src) if src.exists() else "",
                   "size": geo["size"]},
        "camera": {"fov_deg": geo["fov_deg"],
                   "K": np.asarray(geo["K"]).tolist(),
                   "position_in_room": [round(float(x), 4) for x in cam_pos]},
        "room": {"axes_in_camera": np.asarray(geo["axes"]).tolist(),
                 "bounds_min": bmin.tolist(), "bounds_max": bmax.tolist(),
                 "bounds_min_centered": (bmin - center).tolist(),
                 "bounds_max_centered": (bmax - center).tolist(),
                 "dims": np.asarray(geo["dims"]).tolist(),
                 "confidence": geo["confidence"],
                 "observed": geo.get("observed", {})},
        "faces": {name: {"mask": f"masks/{name}.png",
                         "coverage": float(np.mean(np.asarray(m)))
                         if isinstance(m, np.ndarray) else 0.0}
                  for name, m in masks.items()},
        "lighting": light.to_dict(),
        "environment": {"hdr": "sky.hdr"},
        "maps": {"albedo": "albedo.png", "shading": "shading.png",
                 "roughness": "roughness.png", "metalness": "metalness.png",
                 "specular": "specular.png",
                 "depth16": "depth16.png" if depth is not None else None},
    }
    with open(out / "scene.json", "w", encoding="utf-8") as f:
        json.dump(scene, f, ensure_ascii=False, indent=2)
    files.append(str(out / "scene.json"))

    script = build_blender_preview(scene)
    with open(out / "blender_preview.py", "w", encoding="utf-8") as f:
        f.write(script)
    files.append(str(out / "blender_preview.py"))

    report = ["photo2pbr report", "=" * 40,
              "源: %s" % src.name, "缓存键: %s" % key,
              "房间尺寸(m): %s" % np.round(np.asarray(geo["dims"]), 3).tolist(),
              "置信度: %s" % geo["confidence"],
              "天空拟合: %s (ratio=%.3f, rmse=%.4f)"
              % (light.sky_confidence, light.sky_ratio, light.sky_rmse),
              "太阳: %s (rel=%.2f, angular=%.2f deg)"
              % (light.sun_confidence, light.sun_rel_intensity, light.sun_angular_deg),
              "粗糙度 mean=%.3f 金属度 mean=%.3f"
              % (float(np.mean(rough)), float(np.mean(metal)))]
    with open(out / "report.txt", "w", encoding="utf-8") as f:
        f.write("\n".join(report) + "\n")
    files.append(str(out / "report.txt"))
    return files